### ISSUE TITLE
(story) RecordChange

### ISSUE THREAD

**Issue by benjaminbollen** [eureka-network/substreams-postgres-sync#53]
reference by vf: https://github.com/graphprotocol/graph-node/blob/master/chain/substreams/proto/codec.proto

tasks:
- [x] create `codec.proto` with `message RecordChange` (#57)
- [x] include a manifest for sinking `block headers` that outputs `RecordChange` (#58)
- [ ] in runtime match on `RecordChange`(#62)
- [ ] create new `db` from `cli main`; db should idempotently create namespace read from config if it does not exist yet (#65)
- [ ] call `db.insert` from match in runtime (leave all path `unimplemented!` - does not have to be elegant) (#63)
- [ ] create simple shell script or main.rs under `/tests/index-blockheaders` (from config block_start / opt block_end) t sink the blockheaders (#59)

**Comment by benjaminbollen** [comment]
this issue is an attempt to reach a first demo; it mirrors the notion story `TracedDatabaseChanges`

**Comment by vadim-frolov** [comment]
wip in #57 #58 #59

**Comment by benjaminbollen** [comment]
vadim:

- runtime streamer receives manifest package along with SQL schema (the schema belongs to the manifest)
- the streamer requests a schema handle from the DBLoader `get_table(manifest_meta: &PackageMetadata, sql_schema: &str, module: &str) -> Table`
// we create an auxiliary table with mapping from package metadata (name, version, hash, etc.) to a schema (create schema if not exists <name> - for the namespace)
// table per module using original names
- `table.get_current_cursor() -> pb::Cursor`
- `table.insert(ops: RecordChanges, cursor: Cursor)`
- and `table.flush()`
